"use client";

import { useState } from "react";
import { ReportData } from "@/types/database.types";
import { Button } from "@/components/ui/button";
import { toast } from "sonner";
import { Copy, Check, Printer, X, FileText } from "lucide-react";

interface ReportExportModalProps {
  report: ReportData;
  isOpen: boolean;
  onClose: () => void;
}

export function ReportExportModal({
  report,
  isOpen,
  onClose,
}: ReportExportModalProps) {
  const [copied, setCopied] = useState(false);

  if (!isOpen) return null;

  const { timeframe, metrics, completedItems, taskTypeBreakdown, topTags } =
    report;

  // Build markdown export string
  const markdownContent = [
    `# 📊 Nudger Productivity Report`,
    `**Period:** ${timeframe.label} (${timeframe.subLabel})`,
    ``,
    `## 🎯 Key Metrics`,
    `- **Completion Rate:** ${metrics.completionRate}%${
      metrics.completionRateDelta !== null
        ? ` (${metrics.completionRateDelta >= 0 ? "+" : ""}${metrics.completionRateDelta}% vs prior period)`
        : ""
    }`,
    `- **Total Completed:** ${metrics.totalCompleted} tasks`,
    `- **Scheduled / Actions:** ${metrics.totalScheduled} total`,
    `- **Routine Adherence:** ${metrics.recurringAdherenceRate}%`,
    `- **Subtasks Checked:** ${metrics.totalSubtasksCompleted}`,
    `- **Peak Day:** ${metrics.mostProductiveDay || "N/A"}`,
    ``,
    `## 🧠 Cognitive Cue Impact`,
    `- **With Memory Cues:** ${metrics.cueCompletionRate}% completion rate (${metrics.tasksWithCuesCount} completed)`,
    `- **Without Cues:** ${metrics.nonCueCompletionRate}% completion rate (${metrics.tasksWithoutCuesCount} completed)`,
    `- **Cue Lift:** ${metrics.cueImpactDelta >= 0 ? "+" : ""}${metrics.cueImpactDelta}%`,
    ``,
    `## 📋 Task Breakdown`,
    ...taskTypeBreakdown.map(
      (t) => `- **${t.label}:** ${t.completed} (${t.percentage}%)`,
    ),
    ``,
    topTags.length > 0 ? `## 🏷️ Top Tags` : "",
    ...topTags.map(
      (tag) => `- #${tag.name}: ${tag.count} tasks (${tag.percentage}%)`,
    ),
    topTags.length > 0 ? "" : "",
    `## ✅ Accomplishments (${completedItems.length})`,
    ...completedItems.map(
      (item) =>
        `- [x] **${item.title}** (${item.taskType})${
          item.cueContent ? ` — *Cue: "${item.cueContent}"*` : ""
        }${item.tags.length > 0 ? ` [${item.tags.join(", ")}]` : ""}`,
    ),
    ``,
    `---`,
    `*Generated by Nudger Task Memory System on ${new Date().toLocaleDateString()}*`,
  ]
    .filter(Boolean)
    .join("\n");

  const handleCopy = async () => {
    try {
      await navigator.clipboard.writeText(markdownContent);
      setCopied(true);
      toast.success("Report copied to clipboard!", {
        description: "Markdown formatted summary ready to paste.",
      });
      setTimeout(() => setCopied(false), 2000);
    } catch {
      toast.error("Failed to copy report to clipboard");
    }
  };

  const handlePrint = () => {
    window.print();
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4">
      {/* Backdrop */}
      <div
        className="absolute inset-0 bg-foreground/30 backdrop-blur-sm"
        onClick={onClose}
      />

      {/* Modal Container */}
      <div className="relative border border-border bg-card backdrop-blur-md w-full max-w-2xl rounded-2xl shadow-2xl p-6 overflow-hidden max-h-[85vh] flex flex-col">
        <div className="flex items-center justify-between pb-4 border-b border-border/50">
          <div className="flex items-center gap-2.5">
            <div className="p-2 rounded-xl bg-brand-indigo/10 text-brand-indigo">
              <FileText className="w-4 h-4" />
            </div>
            <div>
              <h2 className="text-base font-bold text-foreground">
                Export Report Summary
              </h2>
              <p className="text-xs text-muted-foreground">{timeframe.label}</p>
            </div>
          </div>

          <button
            onClick={onClose}
            className="p-1 rounded-lg text-muted-foreground hover:text-foreground hover:bg-muted"
          >
            <X className="w-4 h-4" />
          </button>
        </div>

        {/* Preview Area */}
        <div className="my-4 flex-1 overflow-y-auto bg-muted/30 border border-border/40 p-4 rounded-xl font-mono text-xs text-foreground whitespace-pre-wrap leading-relaxed select-text">
          {markdownContent}
        </div>

        {/* Action Buttons */}
        <div className="flex items-center justify-between gap-3 pt-3 border-t border-border/50">
          <Button
            variant="outline"
            size="sm"
            onClick={handlePrint}
            className="text-xs gap-1.5 rounded-xl"
          >
            <Printer className="w-3.5 h-3.5" />
            <span>Print / PDF</span>
          </Button>

          <div className="flex items-center gap-2">
            <Button
              variant="ghost"
              size="sm"
              onClick={onClose}
              className="text-xs rounded-xl"
            >
              Close
            </Button>
            <Button
              size="sm"
              onClick={handleCopy}
              className="text-xs gap-1.5 rounded-xl bg-foreground text-background font-bold shadow-md"
            >
              {copied ? (
                <>
                  <Check className="w-3.5 h-3.5 text-emerald-500" />
                  <span>Copied!</span>
                </>
              ) : (
                <>
                  <Copy className="w-3.5 h-3.5" />
                  <span>Copy Markdown</span>
                </>
              )}
            </Button>
          </div>
        </div>
      </div>
    </div>
  );
}
